Ladder optin
fallenswordhelper/fallenswordhelper pull request #206
Opened 2021-04-20 07:55 UTC by ahanden

Re #185  - Adds a button to allow players to opt in or out of the ladder on the ladder page.

2021-05-08 00:54 UTC, ahanden commented
I used a couple eslint-ignore statements because I was totally confounded on why I got the import/no-named-as-default error.

2021-05-18 20:42 UTC, atompkins reviewed
this isn't quite right. you can tell because callApp should only be used under /app/.
/ladder/ladderStatus should be calling /_dataAccess/daSettings and then dealing with the response
/ladder/toggle should be calling /_dataAccess/daSettings and /_dataAccess/daSettingsFlags
OptIn.svelte should be calling /ladder/ladderStatus & /ladder/toggle

_dataAccess is for accessing the API so the files should resemble the API, the only reason for it's existence is in case of fallback
/app/ is API access so is structured like the API
under /ladder/ is your code where you do what you want with the data received from the API

make sense?

is there any way we can get rid of the .then()'s in OptIn.svelte ?

2021-05-20 12:38 UTC, ahanden commented
DeepScan doesn't seem to recognize how reduce works with a second argument.

2021-05-20 14:26 UTC, atompkins commented
DeepScan is complaining because x !== undefined is always true. nothing can be equal to undefined, even undefined is not equal to undefined. we have /common/isUndefined for this purpose.

2021-05-20 14:37 UTC, ahanden commented
I switched to isUndefined. Just another wat for js, I guess.

2021-05-20 15:12 UTC, atompkins commented
my mistake. hasError cannot return undefined. weirdly it can return an object or false.
your code should read
```if (check) { return check; }```

2021-05-20 15:13 UTC, atompkins requested changes

2021-05-20 15:13 UTC, atompkins commented on src/modules/_dataAccess/fallbacks/settings.js
> +  if (isUndefined(settingsHTML)) {
is this necessary?

2021-05-20 15:38 UTC, atompkins commented on src/modules/ladder/OptIn.svelte
> +  function toggle() {
i think there should be a sendEvent in here

2021-06-23 23:54 UTC, atompkins approved these changes

2021-06-24 00:14 UTC, merged