Migrated helper menu to a svelte object
fallenswordhelper/fallenswordhelper pull request #622
Opened 2023-12-30 18:29 UTC by ahanden

re #540

2023-12-31 17:39 UTC, atompkins commented
There are some good ideas here. It's almost a straight conversion.
I'm concerned about mounting the component on every page load.
Previously we only rendered it on mouseenter.
On my M1 with 6x CPU throttle it only takes 6ms.
It's possible that the new version of svelte addresses some of the
performance issues. I just haven't had time recently to properly
look into it. I'll setup an environment on a Pi4 to see.

Rather than a straight conversion I would like to use Modal.svelte.
I was hoping to use some of the behaviour like click anywhere to
close.
Your version doesn't close the menu when something gets
clicked. This was something I added "recently" #593. I don't like
it hanging around until you click on it to close it.

I like functionLookup, it's nice and explicit. I don't think you need
'type' though. An item either has a function or a href.
I don't understand why dev quick links isn't part of
functionLookup though.
I don't understand why the hasOwnProperty check is needed?

sendMsg event is missing and I'd like events on href as well.

2023-12-31 18:21 UTC, ahanden commented
Yeah, the `hasOwnProperty ` bit was from my brain crossing wires. I've been coding a lot in python again.

2024-01-01 11:25 UTC, atompkins commented
on the Pi4 unthrottled, injectHelperMenu takes 52ms.
for context injectQuickLinks takes 34ms.
i'm thinking we can live with that.
just bear it in mind if we add any more.

2024-01-02 02:35 UTC, atompkins requested changes
Apart from a couple of minor niggles the main issue here is positioning. It was surprising to see the menu in the centre of the page. This is most likely the reason I hadn't tackled it 😝 
Also in terms of ergonomics, when you select a modal function, the menu and the background disappear and then the new modal appears with the background again. I think it would be better if the new modal stacked on top before the menu disappears. Less jarring?

2024-01-02 02:35 UTC, atompkins commented on src/modules/chrome/helperMenu/injectHelperMenu.js
> +  startApp({}, target);
needs guard

2024-01-02 02:35 UTC, atompkins commented on src/modules/chrome/helperMenu/functionLookup.js
> +        label: 'Inventory Manager', hrefn: `${notepadBlankUrl}invmanagernew`,
hrefn looks like a typo or a bad merge?

2024-01-02 02:35 UTC, atompkins commented on src/modules/chrome/helperMenu/HelperMenu.svelte
> +<Modal visible={ showMenu } on:close={ toggle }>
is there a way to make the modal appear underneath the HelperMenu toggle button?

2024-01-02 02:35 UTC, atompkins commented on src/modules/chrome/helperMenu/HelperMenu.svelte
> +              onclick="openQuickMsgDialog('{ menuItem.playerName }');">
i particularly don't like inline js getting eval'ed. onclick shows up in the DOM whereas on:click doesn't.
there are 3 lines of code being executed on:click. i think this should be in a function.
alternatively you can have multiple on:click, might be ugly though.

2024-01-08 04:14 UTC, ahanden commented
>  Also in terms of ergonomics, when you select a modal function, the menu and the background disappear and then the new modal appears with the background again. I think it would be better if the new modal stacked on top before the menu disappears. Less jarring?

I'm stumped on how to do this one.

2024-01-08 17:42 UTC, atompkins commented
1. functionLookup contains "Buff Log" twice. The one in "Guild" looks like a copy paste error?
2. For the open/close thing i'd play around with awaiting the loader. i tried returning the runDefault from a few of the loaders and it seemed ok. i'm not entirely convinced it's correct though.
3. there is a weird positioning problem if you don't move "HelperMenu"
![image](https://github.com/fallenswordhelper/fallenswordhelper/assets/6729161/a2ec7cd9-b3c0-4532-9c3e-becd6b1f3f2e)
![image](https://github.com/fallenswordhelper/fallenswordhelper/assets/6729161/a2612b9b-adca-4dea-9b7a-ba7fd0ef5d80)
i'm really not convinced about this approach but i don't have time to experiment right now. i was expecting to make the modal relative to the "HelperMenu" button.

2024-01-10 17:22 UTC, ahanden commented
I ended up removing the Modal.svelte again. I know the "click anywhere to close" feature may be nice, but I really don't think the benefit is worth the cost.

Here the menu moves with the button (javascript free), there's no complicated queuing between svelte modules, and the user can still see their page while the menu is open.

2024-01-12 10:41 UTC, merged