Ajax to app
fallenswordhelper/fallenswordhelper pull request #625
Opened 2024-01-08 04:58 UTC by ahanden

re  #167

2024-01-12 12:22 UTC, atompkins commented
are you doing more on this?

2024-01-13 17:19 UTC, ahanden commented
Yeah, I've got a list of files to update from ajax to app still.

2024-01-17 12:01 UTC, atompkins commented
so this is interesting, when using `ajax` for `equip`, `drop` and `send`, if it fails it pops up a dialog with the error message. by converting it to the app i think any errors are lost, no?

2024-01-18 22:26 UTC, ahanden commented
> so this is interesting, when using `ajax` for `equip`, `drop` and `send`, if it fails it pops up a dialog with the error message. by converting it to the app i think any errors are lost, no?

Looks like error dialogues were put directly into the ajax functions. Definitely makes sense to keep the error reporting, but I'll move it out of the app and ajax calls themselves. Should I be trying to switch the messages to those little grey popups in the top right now?

2024-01-18 23:47 UTC, atompkins commented
yes i would use the toast notification

2024-01-29 04:09 UTC, ahanden commented
The rest of the ajax calls I found aren't "easy" fixes.

2024-02-07 18:25 UTC, atompkins commented
this is hard. next time, separate PR's for each one.

- i think ajax/equipItem.js is no longer used?

this comment is WIP

2024-02-07 20:25 UTC, atompkins requested changes
just a couple of issues to address

2025-01-31 16:38 UTC, atompkins commented
I've ported over what I can. Guild Report, Inventory and backpack will have to wait.

2025-01-31 16:38 UTC, closed without merging